version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"

  backend:
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - localstack
    image: northehw:be
    environment:
      DB_HOST: db
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"

  frontend:
    profiles:
      - localstack
    image: northehw:fe
    environment:
      API_URL: http://backend:3000/api
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3001:3000"
